trigger: none 
pool: Azure Pipelines

jobs:
- job: Terraform_plan
  dependsOn: scanning
  steps:
  - task: TerraformInstaller@1
    displayName: Tool install
    inputs:
      terraformVersion: 'latest'
  - task: TerraformTask@5
    displayName: Terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
      backendServiceArm: 'svctoazure'
      backendAzureRmStorageAccountName: 'storagetest17'
      backendAzureRmContainerName: 'container17'
      backendAzureRmKey: 'terraform.tfstae'

  - task: TerraformTask@5
    displayName: Terraform plan
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
      environmentServiceNameAzureRM: 'svctoazure'
    
- job: scanning 
  steps:
  - task: tfsec@1
    inputs:
      version: 'v1.26.0'
      dir: '$(System.DefaultWorkingDirectory)/dev'
 
- job: manual_validation
  dependsOn: Terraform_plan
  pool: server
  steps:
  - task: ManualValidation@1
    displayName: Manual validate
    inputs:
      notifyUsers: 'ashutosh.pal26@outlook.com'
      approvers: 'ashutosh.pal26@outlook.com'


- job: Terraform_apply  
  dependsOn: manual_validation
  steps:
  - task: TerraformTask@5
    displayName: Terraform init
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
      backendServiceArm: 'svctoazure'
      backendAzureRmStorageAccountName: 'storagetest17'
      backendAzureRmContainerName: 'container17'
      backendAzureRmKey: 'terraform.tfstae'
  - task: TerraformTask@5
    displayName: Terraform apply
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
      environmentServiceNameAzureRM: 'svctoazure'
